[supervisord]
nodaemon=true
user=www-data               # ВАЖЛИВО: вкажіть користувача тут
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
